# SPDX-License-Identifier: GPL-3.0-or-later
"""Build an original, unbranded cosmetics-jar studio scene in Blender 4.4.

No third-party assets, fonts, textures, logos, or reference models are used.
All meshes and materials are generated by this script. Existing scenes and
objects are preserved: this script creates and activates a new scene.

Run with Blender, not ordinary Python:
    Blender --background --python create_scene.py -- --output-dir ./output-v1

Outputs: editable .blend, product-only static .glb, and 1024-square beauty PNG.
The .blend contains a 6-second / 24-fps turntable, frames 1 through 144.
Render that animation separately; this script renders just the still image.
Existing output files are never overwritten. Choose a fresh output directory
or a different --name for another version.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import re
import sys

import bpy
from mathutils import Vector


SEGMENTS = 160
FPS = 24
FRAME_START = 1
FRAME_END = 144
BASE_ANGLE = math.radians(-12)


def cli_args() -> argparse.Namespace:
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--name", default="neutral-cosmetic-jar")
    parser.add_argument("--samples", type=int, default=128)
    parser.add_argument("--skip-still", action="store_true",
                        help="Save scene and GLB without rendering the PNG.")
    parser.add_argument("--skip-glb", action="store_true",
                        help="Save and render the scene; export the model separately.")
    args = parser.parse_args(argv)
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{0,79}", args.name):
        parser.error("--name must be a short ASCII filename stem.")
    if not 16 <= args.samples <= 512:
        parser.error("--samples must be between 16 and 512.")
    return args


def linear_rgb(hex_color: str) -> tuple[float, float, float, float]:
    def linear(v: float) -> float:
        return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4
    values = [int(hex_color[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    return (*[linear(v) for v in values], 1.0)


def material(name: str, color: str, roughness: float,
             metallic: float = 0, coat: float = 0) -> bpy.types.Material:
    result = bpy.data.materials.new(name)
    result.use_nodes = True
    shader = result.node_tree.nodes.get("Principled BSDF")
    shader.inputs["Base Color"].default_value = linear_rgb(color)
    shader.inputs["Roughness"].default_value = roughness
    shader.inputs["Metallic"].default_value = metallic
    shader.inputs["Coat Weight"].default_value = coat
    shader.inputs["Coat Roughness"].default_value = 0.26
    result.diffuse_color = linear_rgb(color)
    result.roughness = roughness
    result.metallic = metallic
    return result


def profile_mesh(name: str, collection: bpy.types.Collection,
                 rings: list[tuple[float, float]], rx: float, ry: float,
                 power: float, mat: bpy.types.Material,
                 segments: int = SEGMENTS) -> bpy.types.Object:
    """Closed surface of superelliptic rings; rounded edges are real geometry."""
    vertices = []
    for z, scale in rings:
        for index in range(segments):
            theta = math.tau * index / segments
            cos_t, sin_t = math.cos(theta), math.sin(theta)
            x = rx * scale * math.copysign(abs(cos_t) ** (2 / power), cos_t)
            y = ry * scale * math.copysign(abs(sin_t) ** (2 / power), sin_t)
            vertices.append((x, y, z))
    faces = [tuple(reversed(range(segments)))]
    for row in range(len(rings) - 1):
        for index in range(segments):
            nxt = (index + 1) % segments
            faces.append((row * segments + index, row * segments + nxt,
                          (row + 1) * segments + nxt,
                          (row + 1) * segments + index))
    faces.append(tuple((len(rings) - 1) * segments + n for n in range(segments)))
    mesh = bpy.data.meshes.new(name + "_mesh")
    mesh.from_pydata(vertices, [], faces)
    mesh.materials.append(mat)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    for polygon in mesh.polygons:
        polygon.use_smooth = len(polygon.vertices) == 4
    return obj


def point_at(obj: bpy.types.Object, target: tuple[float, float, float]) -> None:
    obj.rotation_euler = (Vector(target) - obj.location).to_track_quat('-Z', 'Y').to_euler()


def area_light(collection: bpy.types.Collection, name: str,
               position: tuple[float, float, float], energy: float,
               size: float, target: tuple[float, float, float],
               color: tuple[float, float, float] = (1.0, 1.0, 1.0),
               size_y: float | None = None) -> None:
    light = bpy.data.lights.new(name, type='AREA')
    light.energy = energy
    light.color = color
    light.shape = 'RECTANGLE'
    light.size = size
    light.size_y = size_y or size
    obj = bpy.data.objects.new(name, light)
    collection.objects.link(obj)
    obj.location = position
    point_at(obj, target)


def linear_animation(obj: bpy.types.Object) -> None:
    """Support both legacy and Blender 4.4 layered action F-curves."""
    action = obj.animation_data.action
    curves = []
    try:
        curves.extend(action.fcurves)
    except (AttributeError, RuntimeError):
        pass
    for layer in getattr(action, "layers", []):
        for strip in layer.strips:
            for bag in getattr(strip, "channelbags", []):
                curves.extend(bag.fcurves)
    seen = set()
    for curve in curves:
        pointer = curve.as_pointer()
        if pointer in seen:
            continue
        seen.add(pointer)
        for point in curve.keyframe_points:
            point.interpolation = 'LINEAR'
    if not seen:
        raise RuntimeError("Could not locate turntable animation curves.")


def build_scene(samples: int) -> tuple[bpy.types.Scene, list[bpy.types.Object]]:
    scene = bpy.data.scenes.new("Original Cosmetic Jar | Studio")
    if bpy.context.window is not None:
        bpy.context.window.scene = scene
    product_collection = bpy.data.collections.new("PRODUCT | Exportable geometry")
    studio_collection = bpy.data.collections.new("STUDIO | Excluded from GLB")
    scene.collection.children.link(product_collection)
    scene.collection.children.link(studio_collection)
    scene.unit_settings.system = 'METRIC'
    scene.unit_settings.scale_length = 0.1

    ivory = material("Ivory | satin ceramic-look polymer", "E7DFCC", 0.31, coat=0.22)
    graphite = material("Graphite | satin cap", "333738", 0.25, metallic=0.12, coat=0.16)
    champagne = material("Champagne | brushed metallic trim", "CDB68D", 0.28, metallic=0.84)
    gasket_mat = material("Recess | dark gasket", "222626", 0.54)
    stone = material("Pedestal | warm limestone tone", "C9BFAE", 0.68)
    backdrop = material("Backdrop | warm mineral", "B6AE9F", 0.85)

    root = bpy.data.objects.new("Turntable_Product", None)
    product_collection.objects.link(root)
    root.empty_display_type = 'PLAIN_AXES'
    root.empty_display_size = 0.25
    product = [root]

    body = profile_mesh(
        "Jar_Body", product_collection,
        [(0.168, .88), (0.171, .92), (0.180, .965), (0.194, .989),
         (0.215, 1.0), (0.245, 1.0), (0.960, 1.0),
         (1.003, .998), (1.038, .984), (1.063, .962),
         (1.075, .929), (1.078, .91)],
        .48, .37, 3.35, ivory)
    gasket = profile_mesh(
        "Lid_Recess", product_collection,
        [(1.074, .94), (1.079, 1.0), (1.092, 1.0), (1.094, .96)],
        .467, .358, 3.35, gasket_mat)
    trim = profile_mesh(
        "Champagne_Collar", product_collection,
        [(1.088, .974), (1.091, .998), (1.097, 1.0),
         (1.113, 1.0), (1.116, .981)],
        .486, .376, 3.35, champagne)
    cap = profile_mesh(
        "Graphite_Lid", product_collection,
        [(1.108, .963), (1.112, .983), (1.120, .997),
         (1.132, 1.0), (1.250, 1.0), (1.270, .996),
         (1.284, .982), (1.290, .957), (1.292, .925)],
        .489, .379, 3.35, graphite)
    for obj in (body, gasket, trim, cap):
        obj.parent = root
        obj["original_asset"] = True
        obj["design_note"] = "Unbranded conceptual cosmetics packaging; not a manufacturing drawing."
        product.append(obj)

    # The key beyond the playback range avoids a duplicated final video frame.
    root.rotation_euler.z = BASE_ANGLE
    root.keyframe_insert(data_path="rotation_euler", index=2, frame=FRAME_START)
    root.rotation_euler.z = BASE_ANGLE + math.tau
    root.keyframe_insert(data_path="rotation_euler", index=2, frame=FRAME_END + 1)
    linear_animation(root)

    profile_mesh(
        "Studio_Pedestal", studio_collection,
        [(0.005, .972), (0.012, .991), (0.025, 1.0),
         (.137, 1.0), (.153, .991), (.163, .972)],
        .83, .83, 2.0, stone)
    plane_mesh = bpy.data.meshes.new("Backdrop_mesh")
    plane_mesh.from_pydata([(-100, -100, 0), (100, -100, 0),
                           (100, 100, 0), (-100, 100, 0)], [], [(0, 1, 2, 3)])
    plane_mesh.materials.append(backdrop)
    plane_mesh.update()
    floor = bpy.data.objects.new("Studio_Backdrop", plane_mesh)
    studio_collection.objects.link(floor)

    camera_data = bpy.data.cameras.new("Studio_Camera")
    camera = bpy.data.objects.new("Studio_Camera", camera_data)
    studio_collection.objects.link(camera)
    camera.location = (3.1, -5.8, 3.2)
    point_at(camera, (0, 0, .64))
    camera_data.type = 'ORTHO'
    camera_data.ortho_scale = 2.23
    camera_data.lens = 70
    camera_data.clip_start = .01
    camera_data.clip_end = 200
    scene.camera = camera
    area_light(studio_collection, "Key | tall softbox", (-3.0, -4.1, 4.6),
               460, 3.0, (0, 0, .65), (1.0, .94, .84), size_y=4.0)
    area_light(studio_collection, "Fill | broad neutral", (3.8, -2.0, 2.5),
               135, 2.8, (0, 0, .7), (.88, .94, 1.0), size_y=3.2)
    area_light(studio_collection, "Rim | upper strip", (1.4, 2.8, 3.8),
               380, 2.5, (0, 0, .8), (1.0, .96, .89), size_y=1.2)
    area_light(studio_collection, "Top | cap reflection", (-.4, .6, 5.0),
               65, 2.4, (0, 0, 0))

    world = bpy.data.worlds.new("Studio_World")
    world.use_nodes = True
    world.node_tree.nodes["Background"].inputs["Color"].default_value = linear_rgb("DED9CF")
    world.node_tree.nodes["Background"].inputs["Strength"].default_value = .24
    scene.world = world
    scene.render.engine = 'BLENDER_EEVEE_NEXT'
    if hasattr(scene, "eevee") and hasattr(scene.eevee, "taa_render_samples"):
        scene.eevee.taa_render_samples = samples
    scene.render.resolution_x = 1024
    scene.render.resolution_y = 1024
    scene.render.resolution_percentage = 100
    scene.render.film_transparent = False
    scene.render.image_settings.file_format = 'PNG'
    scene.render.image_settings.color_mode = 'RGB'
    scene.render.image_settings.color_depth = '8'
    scene.render.fps = FPS
    scene.render.fps_base = 1.0
    scene.frame_start = FRAME_START
    scene.frame_end = FRAME_END
    scene.view_settings.view_transform = 'AgX'
    try:
        scene.view_settings.look = 'AgX - Medium High Contrast'
    except TypeError:
        pass
    scene.view_settings.exposure = .1
    scene.view_settings.gamma = 1.0
    scene.frame_set(FRAME_START)
    scene["asset_origin"] = "Original procedural geometry; no third-party assets."
    scene["turntable"] = "24 fps; render frames 1-144 inclusive; 360-degree key at frame 145."
    scene["publication_note"] = "Self-produced fictional packaging concept, not a customer project."
    scene["manufacturing_note"] = "Visual prototype only; no interior/thread/tolerance engineering."
    return scene, product


def export_product_glb(scene: bpy.types.Scene, product: list[bpy.types.Object],
                       destination: Path) -> None:
    """Export only this product, in metres, then restore its studio placement.

    Blender 4.4's glTF exporter traverses every scene unless use_active_scene is
    set. Traversal changes window.scene, so do not pin scene/view_layer with
    temp_override during this operation. Its scene unit scale also needs an
    explicit product transform to produce the intended glTF metre dimensions.
    """
    if bpy.context.window is None:
        raise RuntimeError("An active Blender window context is required for GLB export.")
    bpy.context.window.scene = scene
    view_layer = scene.view_layers[0]
    view_layer.update()
    bpy.context.evaluated_depsgraph_get().update()
    root = next(obj for obj in product if obj.type == 'EMPTY')
    original_scale = root.scale.copy()
    original_location = root.location.copy()
    unit_scale = scene.unit_settings.scale_length
    bottom = min((obj.matrix_world @ vertex.co).z
                 for obj in product if obj.type == 'MESH'
                 for vertex in obj.data.vertices)
    try:
        root.scale = original_scale * unit_scale
        root.location = original_location * unit_scale
        root.location.z -= bottom * unit_scale
        for obj in view_layer.objects:
            obj.select_set(obj in product, view_layer=view_layer)
        view_layer.objects.active = next(obj for obj in product if obj.type == 'MESH')
        view_layer.update()
        bpy.context.evaluated_depsgraph_get().update()
        result = bpy.ops.export_scene.gltf(
            filepath=str(destination), export_format='GLB',
            use_selection=True, use_active_scene=True, export_apply=False,
            export_animations=False, export_cameras=False, export_lights=False,
            export_extras=False, export_yup=True)
        if result != {'FINISHED'}:
            raise RuntimeError("Product GLB export did not finish.")
    finally:
        root.scale = original_scale
        root.location = original_location
        bpy.context.window.scene = scene
        view_layer.update()
        bpy.context.evaluated_depsgraph_get().update()


def main() -> None:
    args = cli_args()
    output_dir = args.output_dir.expanduser().resolve()
    targets = {
        "blend": output_dir / (args.name + ".blend"),
        "glb": output_dir / (args.name + ".glb"),
        "still": output_dir / (args.name + "-beauty.png"),
        "manifest": output_dir / (args.name + "-manifest.json"),
    }
    existing = [str(path) for path in targets.values() if path.exists()]
    if existing:
        raise FileExistsError("Refusing to overwrite existing output: " + ", ".join(existing))
    output_dir.mkdir(parents=True, exist_ok=True)
    previous_scene_names = [scene.name for scene in bpy.data.scenes]
    scene, product = build_scene(args.samples)
    scene.render.filepath = "//" + targets["still"].name

    if not args.skip_glb:
        export_product_glb(scene, product, targets["glb"])
    # Product scale/placement is restored before saving the editable studio.
    # Saving before rendering preserves the editable asset if rendering fails.
    bpy.ops.wm.save_as_mainfile(filepath=str(targets["blend"]), check_existing=True)
    if not args.skip_still:
        try:
            scene.render.filepath = str(targets["still"])
            bpy.ops.render.render(write_still=True, scene=scene.name)
        finally:
            scene.render.filepath = "//" + targets["still"].name

    manifest = {
        "asset": "Original unbranded rounded-rectangle cosmetic jar",
        "blender_version": bpy.app.version_string,
        "script_license": "GPL-3.0-or-later",
        "third_party_assets": [],
        "fictional_self_produced_demo": True,
        "scene": scene.name,
        "previous_scenes_preserved": previous_scene_names,
        "geometry_parts": [obj.name for obj in product if obj.type == 'MESH'],
        "product_mesh_count": 4,
        "glb_scope": "Static product meshes and their transform parent only; no studio objects.",
        "glb_units": "metres; explicit product scaling; product bottom at zero",
        "animation": {"fps": FPS, "frame_start": FRAME_START,
                      "frame_end": FRAME_END, "seconds": 6,
                      "rotation_degrees": 360, "loop_endpoint_frame": 145,
                      "interpolation": "LINEAR", "video_rendered": False},
        "still": {"width": 1024, "height": 1024,
                  "engine": "BLENDER_EEVEE_NEXT", "rendered": not args.skip_still},
        "outputs": {key: path.name for key, path in targets.items()
                    if (key != "still" or not args.skip_still)
                    and (key != "glb" or not args.skip_glb)},
        "limitations": ["Visual prototype, not a manufacturing-ready package.",
                        "GLB appearance depends on the viewer's lighting and color management.",
                        "Animation is configured in the blend; no video is generated here."],
    }
    with targets["manifest"].open("x", encoding="utf-8") as file:
        json.dump(manifest, file, ensure_ascii=False, indent=2)
        file.write("\n")
    print("Created original cosmetic jar scene:")
    for label, path in targets.items():
        if path.is_file():
            print(f"  {label}: {path}")


if __name__ == "__main__":
    main()
